name: flutter_keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 6.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter_keyboard_visibility_linux: ^1.0.0
  flutter_keyboard_visibility_macos: ^1.0.0
  flutter_keyboard_visibility_web: ^2.0.0
  flutter_keyboard_visibility_windows: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  mockito: ^5.0.17
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jrai.flutter_keyboard_visibility
        pluginClass: FlutterKeyboardVisibilityPlugin
      ios:
        pluginClass: FlutterKeyboardVisibilityPlugin
      web:
        default_package: flutter_keyboard_visibility_web
      macos:
        default_package: flutter_keyboard_visibility_macos
      linux:
        default_package: flutter_keyboard_visibility_linux
      windows:
        default_package: flutter_keyboard_visibility_windows