name: flutter_quill_example
description: "Demonstrates how to use the flutter_quill package."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_quill: ^11.0.0-dev.4
  flutter_quill_extensions: ^11.0.0-dev.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_quill_test: ^11.0.0-dev.2
  integration_test:
    sdk: flutter

dependency_overrides:
  flutter_quill:
    path: ../
  flutter_quill_extensions:
    path: ../flutter_quill_extensions
  flutter_quill_test:
    path: ../flutter_quill_test
  # The flutter_keyboard_visibility_web uses dart:html which is incompatible with WASM,
  #  override it with a modified version that uses the web package instead.
  flutter_keyboard_visibility:
    path: ../packages/flutter_keyboard_visibility/flutter_keyboard_visibility
  flutter_keyboard_visibility_web:
    path: ../packages/flutter_keyboard_visibility/flutter_keyboard_visibility_web

flutter:
  uses-material-design: true
  assets:
    - assets/images/
