name: example
description: A demo for the Flutter Quill
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Flutter Quill Packages
  flutter_quill: ^9.3.4
  dart_quill_delta: ^9.3.4
  flutter_quill_extensions: ^9.3.4
  flutter_quill_test: ^9.3.4
  quill_html_converter: ^9.3.4
  quill_pdf_converter: ^9.3.4
  # No^9.2.10ackages
  path: ^1.8.3
  equatable: ^2.0.5
  cross_file: ^0.3.4
  cached_network_image: ^3.3.1
  pdf: ^3.10.8

  # Bloc libraries
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5

  # Freezed
  freezed_annotation: ^2.4.1

  # Json
  json_annotation: ^4.8.1

  # Plugins
  image_cropper: ^5.0.1
  path_provider: ^2.1.2
  # For drag and drop feature
  desktop_drop: ^0.4.4
  # For picking quill document files
  file_picker: ^8.0.0+1
  # For sharing text
  share_plus: ^8.0.2
  printing: ^5.12.0
  google_fonts: ^6.2.1

dependency_overrides:
  flutter_quill:
    path: ../
  flutter_quill_extensions:
    path: ../flutter_quill_extensions
  dart_quill_delta:
    path: ../dart_quill_delta
  flutter_quill_test:
    path: ../flutter_quill_test
  quill_html_converter:
    path: ../quill_html_converter
  quill_pdf_converter:
    path: ../quill_pdf_converter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

  # Freezed
  freezed: ^2.4.7
  # Json
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  
  fonts:
    - family: monospace
      fonts:
        - asset: assets/fonts/MonoSpace.ttf
    - family: serif
      fonts:
        - asset: assets/fonts/Serif.ttf
    - family: sans-serif
      fonts:
        - asset: assets/fonts/SansSerif.ttf
    - family: ibarra-real-nova
      fonts:
          - asset: assets/fonts/IbarraRealNova-Regular.ttf
    - family: square-peg
      fonts:
        - asset: assets/fonts/SquarePeg-Regular.ttf
    - family: nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: roboto-mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf

flutter_gen: