name: flutter_quill_extensions
description: Embed extensions for flutter_quill to support loading images and videos
version: 11.0.0-dev.7
homepage: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions/
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions/
topics: [editor, text, rich-text-editor, quill, flutter-quill]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

# The versions listed here indicate the minimum required for dependencies 
# and do not affect those used in the client's application.
# For more information, visit:
# https://dart.dev/tools/pub/dependencies#version-constraints
# https://docs.flutter.dev/packages-and-plugins/using-packages#conflict-resolution
# https://dart.dev/tools/pub/versioning
# https://dart.dev/guides/libraries/private-files#pubspec-lock
# https://dart.dev/tools/pub/pubspec#sdk-constraints
dependencies:
  flutter:
    sdk: flutter

  # Dart Packages
  meta: ^1.7.0
  universal_html: ^2.2.4
  path: ^1.8.0

  flutter_quill: ^11.0.0-dev.15
  photo_view: ^0.15.0

  # Plugins
  video_player: ^2.8.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
