name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.5.1
homepage: https://bulletjournal.us/home/index.html
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^7.4.14
  # In case you are working on changes for both libraries,
  # flutter_quill:
  #   path: ~/development/playground/framework_based/flutter/flutter-quill

  http: ^1.1.0
  image_picker: ">=1.0.4"
  photo_view: ^0.14.0
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  math_keyboard: ">=0.2.1"
  universal_html: ^2.2.4

  gal: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
