name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.7.2
homepage: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.6 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Normal packages
  http: ^1.1.0
  path: ^1.8.3
  meta: ^1.9.1
  universal_html: ^2.2.4
  cross_file: ^0.3.3+6

  flutter_quill: ^8.6.0
  photo_view: ^0.14.0

  # Plugins
  video_player: ^2.8.1
  youtube_player_flutter: ^8.1.2
  gal: ^2.1.3
  image_picker: ^1.0.4
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true