name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.2.0
homepage: https://bulletjournal.us/home/index.html
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^7.1.4

  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  video_player: ^2.4.2
  youtube_player_flutter: ^8.1.1
  gallery_saver: ^2.3.2
  math_keyboard: ^0.1.8
  string_validator: ^1.0.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

# The following section is specific to Flutter packages.
flutter:
