name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.6.1
homepage: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor

platforms:
  android:
  ios:
  # linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^8.2.3

  http: ^1.1.0
  photo_view: ^0.14.0
  video_player: ^2.8.1
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.8.0
  universal_html: ^2.2.4
  gal: ^2.1.3
  path: ^1.8.3
  image_picker: ^1.0.4
  math_keyboard: ^0.2.1
  url_launcher: ^6.2.1
  meta: ^1.9.1
  cross_file: ^0.3.3+6

# In case you are working on changes for both libraries
# Comment the dependency_overrides section when publishing the package,
# then uncomment it back, this will be automated later
# dependency_overrides:
#   flutter_quill:
#     path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true