name: flutter_quill
description: A rich text editor built for the modern Android, iOS, web and desktop platforms. It is the WYSIWYG editor and a Quill component for Flutter.
version: 9.3.10
homepage: https://1o24bbs.com/c/bulletjournal/108/
repository: https://github.com/singerdmx/flutter-quill/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/

topics:
  - ui
  - widgets
  - widget
  - rich-text-editor
  - quill

screenshots:
  - description: "Screenshot 1"
    path: example/assets/images/screenshot_1.png
  - description: "Screenshot 2"
    path: example/assets/images/screenshot_2.png
  - description: "Screenshot 3"
    path: example/assets/images/screenshot_3.png
  - description: "Screenshot 4"
    path: example/assets/images/screenshot_4.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Normal packages
  intl: ^0.18.1
  dart_quill_delta: ^9.3.3
  collection: ^1.17.0
  quiver: ^3.2.1
  equatable: ^2.0.5
  meta: ^1.10.0
  html: ^0.15.4

  flutter_colorpicker: ^1.0.3

  # For converting HTML to Quill delta
  markdown: ^7.2.1
  html2md: ^1.3.1
  charcode: ^1.3.1

  # Plugins
  url_launcher: ^6.2.4
  flutter_keyboard_visibility: ^6.0.0
  device_info_plus: ^10.0.1
  super_clipboard: ^0.8.10

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  flutter_quill_test: ^9.3.4
  test: ^1.24.3
  yaml_edit: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
