name: flutter_quill
description: "A rich text editor built for Android, iOS, Web, and desktop platforms. It's the WYSIWYG editor and a Quill component for Flutter."
version: 10.7.4
homepage: https://github.com/singerdmx/flutter-quill/
repository: https://github.com/singerdmx/flutter-quill/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/

topics:
  - ui
  - widgets
  - widget
  - rich-text-editor
  - quill

screenshots:
  - description: "Screenshot 1"
    path: example/assets/images/screenshot_1.png
  - description: "Screenshot 2"
    path: example/assets/images/screenshot_2.png
  - description: "Screenshot 3"
    path: example/assets/images/screenshot_3.png
  - description: "Screenshot 4"
    path: example/assets/images/screenshot_4.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Dart Packages
  intl: ^0.19.0
  dart_quill_delta: ^10.0.0
  collection: ^1.17.0
  quiver: ^3.2.1
  equatable: ^2.0.5
  meta: ^1.10.0
  html: ^0.15.4
  web: ^1.0.0

  flutter_colorpicker: ^1.1.0

  # For converting HTML to Quill delta
  flutter_quill_delta_from_html: ^1.4.1
  markdown: ^7.2.1
  charcode: ^1.3.1

  # Plugins
  url_launcher: ^6.2.4
  flutter_keyboard_visibility: ^6.0.0
  quill_native_bridge: ^10.5.14

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_quill_test: ^10.0.0
  test: ^1.24.3

  # For scripts only
  yaml_edit: ^2.2.1
  yaml: ^3.1.2
  http: ^1.2.1

  path: any
flutter:
  uses-material-design: true
  generate: true
