name: flutter_quill
description: A rich text editor built for the modern Android, iOS, web and desktop platforms. It is the WYSIWYG editor and a Quill component for Flutter.
version: 8.6.4
homepage: https://1o24bbs.com/c/bulletjournal/108
repository: https://github.com/singerdmx/flutter-quill

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor
 - quill

screenshots:
 - description: 'Screenshot 1'
   path: example/assets/images/screenshot_1.png
 - description: 'Screenshot 2'
   path: example/assets/images/screenshot_2.png
 - description: 'Screenshot 3'
   path: example/assets/images/screenshot_3.png
 - description: 'Screenshot 4'
   path: example/assets/images/screenshot_4.png
 
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.6 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Normal packages
  collection: ^1.17.0
  flutter_colorpicker: ^1.0.3
  quiver: ^3.2.1
  characters: ^1.3.0
  diff_match_patch: ^0.4.1
  equatable: ^2.0.5
  flutter_animate: ^4.2.0+1
  meta: ^1.9.1

  # Plugins
  url_launcher: ^6.1.14
  flutter_keyboard_visibility: ^5.4.1
  device_info_plus: ^9.1.0
  pasteboard: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_quill_test: ^0.0.4
  test: ^1.24.3
  intl_translation: ^0.18.2

flutter:
  uses-material-design: true
  generate: true
