name: flutter_quill
description: A rich text editor built for the modern Android, iOS, web and desktop platforms. It is the WYSIWYG editor and a Quill component for Flutter.
version: 8.1.9
homepage: https://1o24bbs.com/c/bulletjournal/108
repository: https://github.com/singerdmx/flutter-quill

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor
 - quill

screenshots:
 - description: 'Screenshot 1'
   path: example/assets/images/1.png
 - description: 'Screenshot 2'
   path: example/assets/images/2.png
 - description: 'Screenshot 3'
   path: example/assets/images/3.png
 - description: 'Screenshot 4'
   path: example/assets/images/4.png
 
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.3 <4.0.0'
  # sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.4.1
  quiver: ^3.2.1
  url_launcher: ^6.1.14
  pedantic: ^1.11.1
  characters: ^1.3.0
  diff_match_patch: ^0.4.1
  i18n_extension: ^9.0.2
  device_info_plus: ^9.1.0
  platform: ^3.1.0
  pasteboard: ^0.2.0
  equatable: ^2.0.5
  flutter_animate: ^4.2.0+1

  flutter_test:
    sdk: flutter
  meta: ^1.9.1

flutter: null