name: flutter_keyboard_visibility_platform_interface
description: A common platform interface for the flutter_keyboard_visibility plugin.
version: 2.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.0.0 <2.0.0"
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter