name: quill_html_converter
description: A extension for flutter_quill package to add support for dealing with conversion to/from html
version: 9.0.0-dev-9
homepage: https://github.com/singerdmx/flutter-quill/tree/master/packages/quill_html_converter/
repository: https://github.com/singerdmx/flutter-quill/tree/master/packages/quill_html_converter/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/tree/master/packages/quill_html_converter/

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor
 - quill

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^9.0.0-dev-6
  vsc_quill_delta_to_html: ^1.0.3
  html2md: ^1.3.1
  # markdown: ^7.1.1
  # delta_markdown_converter: ^0.0.3-dev
  markdown: ^7.1.1
  charcode: ^1.3.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true