name: quill_html_converter
description: A extension for flutter_quill package to add support for dealing with conversion to/from html
version: 9.3.10
homepage: https://github.com/singerdmx/flutter-quill/tree/master/quill_html_converter/
repository: https://github.com/singerdmx/flutter-quill/tree/master/quill_html_converter/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/tree/master/quill_html_converter/

topics:
 - ui
 - widgets
 - widget
 - rich-text-editor
 - quill

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vsc_quill_delta_to_html: ^1.0.4
  html2md: ^1.3.1
  markdown: ^7.2.2
  charcode: ^1.3.1
  collection: ^1.18.0
  dart_quill_delta: ^9.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  test: ^1.24.9

flutter:

  uses-material-design: true