name: ğŸ“ Changelog File Check

# This workflow only validates if the CHANGELOG.md file was updated and doesn't validate the format.

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master

jobs:
  changelog:
    name: ğŸ” Verify Changelog Modification
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Check if CHANGELOG.md was modified
        uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md
