name: ğŸš€ Update GitHub Release Notes from CHANGELOG.md

on:
  release:
    types: [published]

jobs:
  release-notes:
    name: ğŸ“ Publish Release Notes from Changelog
    permissions:
      # Required for updating GitHub release notes
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v4

      - name: âœ‚ï¸ Extract Release Notes from CHANGELOG.md
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          changelog_file: CHANGELOG.md
          release_notes_file: RELEASE_NOTES.md

      - name: ğŸ–‹ï¸ Update Release Notes
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: "RELEASE_NOTES.md"
