name: ğŸš€ Update GitHub Release Notes from CHANGELOG.md

on:
  release:
    types: [published]

jobs:
  release-notes:
    name: ğŸ“ Publish Release Notes from Changelog
    permissions:
      # Required for updating GitHub release notes
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v4

      - name: âœ‚ï¸ Extract Release Notes from CHANGELOG.md
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          changelog_file: CHANGELOG.md

      - name: ğŸ–‹ï¸ Update Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit ${{ github.event.release.tag_name }} --notes "${{ steps.extract-release-notes.outputs.release_notes }}"
