name: ğŸ§ª Run Tests

# TODO: Split the tests into tests.yml and quality checks into checks.yml once start using https://pub.dev/packages/melos

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  tests:
    name: Check lints and tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: ğŸ” Verify Flutter installation
        run: flutter --version

      - name: ğŸ“¥ Install Flutter dependencies
        run: flutter pub get
      
      - name: ğŸ“¦ Install flutter_quill_extensions dependencies
        run: flutter pub get -C flutter_quill_extensions

      - name: ğŸ“¦ Install flutter_quill_test dependencies
        run: flutter pub get -C flutter_quill_test

      - name: ğŸ” Run Flutter analysis
        run: flutter analyze

      - name: ğŸ§¹ Check Dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: ğŸ” Preview Dart proposed changes
        run: dart fix --dry-run

      - name: ğŸ“¦ Check if package is ready for publishing
        run: flutter pub publish --dry-run

      - name: ğŸ§ª Run flutter_quill tests
        run: flutter test

      - name: ğŸ§ª Run flutter_quill_extensions tests
        run: flutter test
        working-directory: flutter_quill_extensions

      - name: ğŸ” Check the translations
        run: dart ./scripts/translations_check.dart

      - name: ğŸ“¥ Install cider
        run: dart pub global activate cider

      # TODO: Need a more strict way to validate the format that uses https://keepachangelog.com/en/1.1.0/
      - name: ğŸ” Validate CHANGELOG.md format
        run: $HOME/.pub-cache/bin/cider list CHANGELOG.md
