name: ğŸ§ª Run Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  tests:
    name: Check lints and tests
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: ğŸ” Verify Flutter installation
        run: flutter --version

      - name: ğŸ“¥ Install Flutter dependencies
        run: flutter pub get
      
      - name: ğŸ“¦ Install flutter_quill_extensions dependencies
        run: flutter pub get -C flutter_quill_extensions

      - name: ğŸ“¦ Install flutter_quill_test dependencies
        run: flutter pub get -C flutter_quill_test

      # TODO: Remove quill_native_bridge packages from here once moved to it's own repo
      # https://github.com/singerdmx/flutter-quill/pull/2230

      - name: ğŸ“¦ Install quill_native_bridge dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge

      - name: ğŸ“¦ Install quill_native_bridge_platform_interface dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_platform_interface

      - name: ğŸ“¦ Install quill_native_bridge_android dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_android

      - name: ğŸ“¦ Install quill_native_bridge_ios dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_ios

      - name: ğŸ“¦ Install quill_native_bridge_macos dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_macos

      - name: ğŸ“¦ Install quill_native_bridge_windows dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_windows

      - name: ğŸ“¦ Install quill_native_bridge_web dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_web

      - name: ğŸ“¦ Install quill_native_bridge_linux dependencies
        run: flutter pub get -C quill_native_bridge/quill_native_bridge_linux

      - name: ğŸ” Run Flutter analysis
        run: flutter analyze

      - name: ğŸ§¹ Check Dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: ğŸ” Preview Dart proposed changes
        run: dart fix --dry-run

      - name: ğŸ“¦ Check if package is ready for publishing
        run: flutter pub publish --dry-run

      - name: ğŸ§ª Run Flutter tests
        run: flutter test

      - name: ğŸ” Check the translations
        run: dart ./scripts/ensure_translations_correct.dart
