name: CI Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Enable Local Dev
        run: ./scripts/enable_local_dev.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Install dart_quill_delta dependencies
        run: flutter pub get -C dart_quill_delta
      
      - name: Install flutter_quill_extensions dependencies
        run: flutter pub get -C flutter_quill_extensions

      - name: Install flutter_quill_test dependencies
        run: flutter pub get -C flutter_quill_test
      
      - name: Install quill_html_converter dependencies
        run: flutter pub get -C quill_html_converter
      
      - name: Install quill_pdf_converter dependencies
        run: flutter pub get -C quill_pdf_converter

      - name: Run flutter analysis
        run: flutter analyze

      - name: Check dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Preview dart proposed changes
        run: dart fix --dry-run

      - name: Check if package is ready for publishing
        run: flutter pub publish --dry-run

      - name: Run flutter tests
        run: flutter test
