name: flutter-quill CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get
      
      - name: Install flutter_quill_extensions dependencies
        run: flutter pub get -C flutter_quill_extensions

      - name: Install flutter_quill_test dependencies
        run: flutter pub get -C flutter_quill_test
      
      - name: Install quill_html_converter dependencies
        run: flutter pub get -C packages/quill_html_converter

      - name: Run flutter analysis
        run: flutter analyze

      - name: Check dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Preview dart proposed changes
        run: dart fix --dry-run

      - name: Check if package is ready for publishing
        run: flutter pub publish --dry-run

      - name: Run flutter tests
        run: flutter test
      
      - name: Flutter Build Web
        run: flutter build web --release --verbose --dart-define=CI=true
        working-directory: ./example
      - name: Flutter Build Linux
        run: flutter build linux --release --verbose --dart-define=CI=true
        working-directory: ./example
